//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common/cs_comm.proto
namespace proto
{
    [global::ProtoBuf.ProtoContract(Name=@"UserStateType")]
    public enum UserStateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserMaskType_BuyNewShop36", Value=36)]
      UserMaskType_BuyNewShop36 = 36
    }
  
}