//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common/cs_proto.proto
// Note: requires additional types generated from: common/cs_comm.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankData")]
  public partial class RankData : global::ProtoBuf.IExtensible
  {
    public RankData() {}
    
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private uint _no;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint no
    {
      get { return _no; }
      set { _no = value; }
    }
    private uint _head;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint head
    {
      get { return _head; }
      set { _head = value; }
    }
    private uint _countroy;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"countroy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint countroy
    {
      get { return _countroy; }
      set { _countroy = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private byte[] _audio;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"audio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] audio
    {
      get { return _audio; }
      set { _audio = value; }
    }
    private uint _upvalue;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"upvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint upvalue
    {
      get { return _upvalue; }
      set { _upvalue = value; }
    }
    private uint? _downvalue;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"downvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint downvalue
    {
      get { return _downvalue?? default(uint); }
      set { _downvalue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool downvalueSpecified
    {
      get { return this._downvalue != null; }
      set { if (value == (this._downvalue== null)) this._downvalue = value ? this.downvalue : (uint?)null; }
    }
    private bool ShouldSerializedownvalue() { return downvalueSpecified; }
    private void Resetdownvalue() { downvalueSpecified = false; }
    
    private uint _logicWorldId;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"logicWorldId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint logicWorldId
    {
      get { return _logicWorldId; }
      set { _logicWorldId = value; }
    }
    private uint _audiolength;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"audiolength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint audiolength
    {
      get { return _audiolength; }
      set { _audiolength = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSRankDataReq")]
  public partial class CSRankDataReq : global::ProtoBuf.IExtensible
  {
    public CSRankDataReq() {}
    
    private uint _ranktype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranktype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ranktype
    {
      get { return _ranktype; }
      set { _ranktype = value; }
    }
    private uint _scopetype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scopetype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scopetype
    {
      get { return _scopetype; }
      set { _scopetype = value; }
    }
    private uint? _reserve;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reserve", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reserve
    {
      get { return _reserve?? default(uint); }
      set { _reserve = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reserveSpecified
    {
      get { return this._reserve != null; }
      set { if (value == (this._reserve== null)) this._reserve = value ? this.reserve : (uint?)null; }
    }
    private bool ShouldSerializereserve() { return reserveSpecified; }
    private void Resetreserve() { reserveSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCRankDataRes")]
  public partial class SCRankDataRes : global::ProtoBuf.IExtensible
  {
    public SCRankDataRes() {}
    
    private uint _ranktype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ranktype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ranktype
    {
      get { return _ranktype; }
      set { _ranktype = value; }
    }
    private uint _scopetype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scopetype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scopetype
    {
      get { return _scopetype; }
      set { _scopetype = value; }
    }
    private uint? _reserve;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"reserve", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reserve
    {
      get { return _reserve?? default(uint); }
      set { _reserve = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reserveSpecified
    {
      get { return this._reserve != null; }
      set { if (value == (this._reserve== null)) this._reserve = value ? this.reserve : (uint?)null; }
    }
    private bool ShouldSerializereserve() { return reserveSpecified; }
    private void Resetreserve() { reserveSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<proto.RankData> _data = new global::System.Collections.Generic.List<proto.RankData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.RankData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RANKTYPE")]
    public enum RANKTYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_LADDER", Value=0)]
      RANK_LADDER = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_HERO", Value=1)]
      RANK_HERO = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_FANS", Value=2)]
      RANK_FANS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_LIVE", Value=3)]
      RANK_LIVE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RANK_GIFT", Value=4)]
      RANK_GIFT = 4
    }
  
}