//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common/cs_proto_ids.proto
// Note: requires additional types generated from: common/cs_comm.proto
namespace proto
{
    [global::ProtoBuf.ProtoContract(Name=@"ProtoID")]
    public enum ProtoID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ProtoID_test", Value=1)]
      ProtoID_test = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ProtoID_LoginReq", Value=2)]
      ProtoID_LoginReq = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ProtoID_LoginRet", Value=3)]
      ProtoID_LoginRet = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSID_RANK_DATA_REQ", Value=170)]
      CSID_RANK_DATA_REQ = 170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCID_RANK_DATA_RSQ", Value=171)]
      SCID_RANK_DATA_RSQ = 171
    }
  
}