//// <auto-generated>
////     Generated by the protocol buffer compiler.  DO NOT EDIT!
////     source: client_level.proto
//// </auto-generated>
//#pragma warning disable 1591, 0612, 3021, 8981
//#region Designer generated code

//using pb = global::Google.Protobuf;
//using pbc = global::Google.Protobuf.Collections;
//using pbr = global::Google.Protobuf.Reflection;
//using scg = global::System.Collections.Generic;
//namespace Protocol {

//  /// <summary>Holder for reflection information generated from client_level.proto</summary>
//  public static partial class ClientLevelReflection {

//    #region Descriptor
//    /// <summary>File descriptor for client_level.proto</summary>
//    public static pbr::FileDescriptor Descriptor {
//      get { return descriptor; }
//    }
//    private static pbr::FileDescriptor descriptor;

//    static ClientLevelReflection() {
//      byte[] descriptorData = global::System.Convert.FromBase64String(
//          string.Concat(
//            "ChJjbGllbnRfbGV2ZWwucHJvdG8SCHByb3RvY29sImkKCExldmVsQ2ZnEi4K",
//            "CnBvaW50X2xpc3QYASABKAsyGi5wcm90b2NvbC5BY3Rpb25Qb2ludEdyb3Vw",
//            "Ei0KCWFyZWFfbGlzdBgCIAEoCzIaLnByb3RvY29sLlRyaWdnZXJBcmVhR3Jv",
//            "dXAiNwoQQWN0aW9uUG9pbnRHcm91cBIjCgRsaXN0GAEgAygLMhUucHJvdG9j",
//            "b2wuQWN0aW9uUG9pbnQiYQoLQWN0aW9uUG9pbnQSHwoDcG9zGAEgASgLMhIu",
//            "cHJvdG9jb2wuQ2xpZW50VjMSIwoHZm9yd2FyZBgCIAEoCzISLnByb3RvY29s",
//            "LkNsaWVudFYzEgwKBHR5cGUYAyABKAUiNwoQVHJpZ2dlckFyZWFHcm91cBIj",
//            "CgRsaXN0GAEgAygLMhUucHJvdG9jb2wuVHJpZ2dlckFyZWEi0AEKC1RyaWdn",
//            "ZXJBcmVhEg0KBXNoYXBlGAEgASgFEiAKBHNpemUYAiABKAsyEi5wcm90b2Nv",
//            "bC5DbGllbnRWMxIRCgljb25kaXRpb24YAyABKAUSGAoQY2hlY2tfbGF5ZXJf",
//            "bGlzdBgEIAMoBRIOCgZlZmZlY3QYBSABKAUSHwoDcG9zGAYgASgLMhIucHJv",
//            "dG9jb2wuQ2xpZW50VjMSIwoHZm9yd2FyZBgHIAEoCzISLnByb3RvY29sLkNs",
//            "aWVudFYzEg0KBWNmZ0lkGAggASgFIjIKC0V5c1ZvdGVSb29tEiMKBGxpc3QY",
//            "ASADKAsyFS5wcm90b2NvbC5FeXNWb3RlSXRlbSJTCgtFeXNWb3RlSXRlbRIf",
//            "CgNwb3MYASABKAsyEi5wcm90b2NvbC5DbGllbnRWMxIjCgdmb3J3YXJkGAIg",
//            "ASgLMhIucHJvdG9jb2wuQ2xpZW50VjMiKwoIQ2xpZW50VjMSCQoBeBgBIAEo",
//            "BRIJCgF5GAIgASgFEgkKAXoYAyABKAUiaQoTR2FtZVBsYXlUcmlnZ2VyQXJl",
//            "YRIfCgNwb3MYASABKAsyEi5wcm90b2NvbC5DbGllbnRWMxIjCgdmb3J3YXJk",
//            "GAIgASgLMhIucHJvdG9jb2wuQ2xpZW50VjMSDAoEc2l6ZRgDIAEoBUIVWhMu",
//            "L3Byb3RvY29sO3Byb3RvY29sYgZwcm90bzM="));
//      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
//          new pbr::FileDescriptor[] { },
//          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
//            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.LevelCfg), global::Protocol.LevelCfg.Parser, new[]{ "PointList", "AreaList" }, null, null, null, null),
//            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.ActionPointGroup), global::Protocol.ActionPointGroup.Parser, new[]{ "List" }, null, null, null, null),
//            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.ActionPoint), global::Protocol.ActionPoint.Parser, new[]{ "Pos", "Forward", "Type" }, null, null, null, null),
//            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.TriggerAreaGroup), global::Protocol.TriggerAreaGroup.Parser, new[]{ "List" }, null, null, null, null),
//            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.TriggerArea), global::Protocol.TriggerArea.Parser, new[]{ "Shape", "Size", "Condition", "CheckLayerList", "Effect", "Pos", "Forward", "CfgId" }, null, null, null, null),
//            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.EysVoteRoom), global::Protocol.EysVoteRoom.Parser, new[]{ "List" }, null, null, null, null),
//            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.EysVoteItem), global::Protocol.EysVoteItem.Parser, new[]{ "Pos", "Forward" }, null, null, null, null),
//            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.ClientV3), global::Protocol.ClientV3.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
//            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.GamePlayTriggerArea), global::Protocol.GamePlayTriggerArea.Parser, new[]{ "Pos", "Forward", "Size" }, null, null, null, null)
//          }));
//    }
//    #endregion

//  }
//  #region Messages
//  public sealed partial class LevelCfg : pb::IMessage<LevelCfg>
//  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      , pb::IBufferMessage
//  #endif
//  {
//    private static readonly pb::MessageParser<LevelCfg> _parser = new pb::MessageParser<LevelCfg>(() => new LevelCfg());
//    private pb::UnknownFieldSet _unknownFields;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pb::MessageParser<LevelCfg> Parser { get { return _parser; } }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pbr::MessageDescriptor Descriptor {
//      get { return global::Protocol.ClientLevelReflection.Descriptor.MessageTypes[0]; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    pbr::MessageDescriptor pb::IMessage.Descriptor {
//      get { return Descriptor; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public LevelCfg() {
//      OnConstruction();
//    }

//    partial void OnConstruction();

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public LevelCfg(LevelCfg other) : this() {
//      pointList_ = other.pointList_ != null ? other.pointList_.Clone() : null;
//      areaList_ = other.areaList_ != null ? other.areaList_.Clone() : null;
//      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public LevelCfg Clone() {
//      return new LevelCfg(this);
//    }

//    /// <summary>Field number for the "point_list" field.</summary>
//    public const int PointListFieldNumber = 1;
//    private global::Protocol.ActionPointGroup pointList_;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ActionPointGroup PointList {
//      get { return pointList_; }
//      set {
//        pointList_ = value;
//      }
//    }

//    /// <summary>Field number for the "area_list" field.</summary>
//    public const int AreaListFieldNumber = 2;
//    private global::Protocol.TriggerAreaGroup areaList_;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.TriggerAreaGroup AreaList {
//      get { return areaList_; }
//      set {
//        areaList_ = value;
//      }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override bool Equals(object other) {
//      return Equals(other as LevelCfg);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public bool Equals(LevelCfg other) {
//      if (ReferenceEquals(other, null)) {
//        return false;
//      }
//      if (ReferenceEquals(other, this)) {
//        return true;
//      }
//      if (!object.Equals(PointList, other.PointList)) return false;
//      if (!object.Equals(AreaList, other.AreaList)) return false;
//      return Equals(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override int GetHashCode() {
//      int hash = 1;
//      if (pointList_ != null) hash ^= PointList.GetHashCode();
//      if (areaList_ != null) hash ^= AreaList.GetHashCode();
//      if (_unknownFields != null) {
//        hash ^= _unknownFields.GetHashCode();
//      }
//      return hash;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override string ToString() {
//      return pb::JsonFormatter.ToDiagnosticString(this);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void WriteTo(pb::CodedOutputStream output) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      output.WriteRawMessage(this);
//    #else
//      if (pointList_ != null) {
//        output.WriteRawTag(10);
//        output.WriteMessage(PointList);
//      }
//      if (areaList_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(AreaList);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(output);
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//      if (pointList_ != null) {
//        output.WriteRawTag(10);
//        output.WriteMessage(PointList);
//      }
//      if (areaList_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(AreaList);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(ref output);
//      }
//    }
//    #endif

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CalculateSize() {
//      int size = 0;
//      if (pointList_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PointList);
//      }
//      if (areaList_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AreaList);
//      }
//      if (_unknownFields != null) {
//        size += _unknownFields.CalculateSize();
//      }
//      return size;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(LevelCfg other) {
//      if (other == null) {
//        return;
//      }
//      if (other.pointList_ != null) {
//        if (pointList_ == null) {
//          PointList = new global::Protocol.ActionPointGroup();
//        }
//        PointList.MergeFrom(other.PointList);
//      }
//      if (other.areaList_ != null) {
//        if (areaList_ == null) {
//          AreaList = new global::Protocol.TriggerAreaGroup();
//        }
//        AreaList.MergeFrom(other.AreaList);
//      }
//      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(pb::CodedInputStream input) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      input.ReadRawMessage(this);
//    #else
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//            break;
//          case 10: {
//            if (pointList_ == null) {
//              PointList = new global::Protocol.ActionPointGroup();
//            }
//            input.ReadMessage(PointList);
//            break;
//          }
//          case 18: {
//            if (areaList_ == null) {
//              AreaList = new global::Protocol.TriggerAreaGroup();
//            }
//            input.ReadMessage(AreaList);
//            break;
//          }
//        }
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//            break;
//          case 10: {
//            if (pointList_ == null) {
//              PointList = new global::Protocol.ActionPointGroup();
//            }
//            input.ReadMessage(PointList);
//            break;
//          }
//          case 18: {
//            if (areaList_ == null) {
//              AreaList = new global::Protocol.TriggerAreaGroup();
//            }
//            input.ReadMessage(AreaList);
//            break;
//          }
//        }
//      }
//    }
//    #endif

//  }

//  public sealed partial class ActionPointGroup : pb::IMessage<ActionPointGroup>
//  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      , pb::IBufferMessage
//  #endif
//  {
//    private static readonly pb::MessageParser<ActionPointGroup> _parser = new pb::MessageParser<ActionPointGroup>(() => new ActionPointGroup());
//    private pb::UnknownFieldSet _unknownFields;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pb::MessageParser<ActionPointGroup> Parser { get { return _parser; } }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pbr::MessageDescriptor Descriptor {
//      get { return global::Protocol.ClientLevelReflection.Descriptor.MessageTypes[1]; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    pbr::MessageDescriptor pb::IMessage.Descriptor {
//      get { return Descriptor; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public ActionPointGroup() {
//      OnConstruction();
//    }

//    partial void OnConstruction();

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public ActionPointGroup(ActionPointGroup other) : this() {
//      list_ = other.list_.Clone();
//      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public ActionPointGroup Clone() {
//      return new ActionPointGroup(this);
//    }

//    /// <summary>Field number for the "list" field.</summary>
//    public const int ListFieldNumber = 1;
//    private static readonly pb::FieldCodec<global::Protocol.ActionPoint> _repeated_list_codec
//        = pb::FieldCodec.ForMessage(10, global::Protocol.ActionPoint.Parser);
//    private readonly pbc::RepeatedField<global::Protocol.ActionPoint> list_ = new pbc::RepeatedField<global::Protocol.ActionPoint>();
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public pbc::RepeatedField<global::Protocol.ActionPoint> List {
//      get { return list_; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override bool Equals(object other) {
//      return Equals(other as ActionPointGroup);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public bool Equals(ActionPointGroup other) {
//      if (ReferenceEquals(other, null)) {
//        return false;
//      }
//      if (ReferenceEquals(other, this)) {
//        return true;
//      }
//      if(!list_.Equals(other.list_)) return false;
//      return Equals(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override int GetHashCode() {
//      int hash = 1;
//      hash ^= list_.GetHashCode();
//      if (_unknownFields != null) {
//        hash ^= _unknownFields.GetHashCode();
//      }
//      return hash;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override string ToString() {
//      return pb::JsonFormatter.ToDiagnosticString(this);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void WriteTo(pb::CodedOutputStream output) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      output.WriteRawMessage(this);
//    #else
//      list_.WriteTo(output, _repeated_list_codec);
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(output);
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//      list_.WriteTo(ref output, _repeated_list_codec);
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(ref output);
//      }
//    }
//    #endif

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CalculateSize() {
//      int size = 0;
//      size += list_.CalculateSize(_repeated_list_codec);
//      if (_unknownFields != null) {
//        size += _unknownFields.CalculateSize();
//      }
//      return size;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(ActionPointGroup other) {
//      if (other == null) {
//        return;
//      }
//      list_.Add(other.list_);
//      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(pb::CodedInputStream input) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      input.ReadRawMessage(this);
//    #else
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//            break;
//          case 10: {
//            list_.AddEntriesFrom(input, _repeated_list_codec);
//            break;
//          }
//        }
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//            break;
//          case 10: {
//            list_.AddEntriesFrom(ref input, _repeated_list_codec);
//            break;
//          }
//        }
//      }
//    }
//    #endif

//  }

//  public sealed partial class ActionPoint : pb::IMessage<ActionPoint>
//  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      , pb::IBufferMessage
//  #endif
//  {
//    private static readonly pb::MessageParser<ActionPoint> _parser = new pb::MessageParser<ActionPoint>(() => new ActionPoint());
//    private pb::UnknownFieldSet _unknownFields;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pb::MessageParser<ActionPoint> Parser { get { return _parser; } }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pbr::MessageDescriptor Descriptor {
//      get { return global::Protocol.ClientLevelReflection.Descriptor.MessageTypes[2]; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    pbr::MessageDescriptor pb::IMessage.Descriptor {
//      get { return Descriptor; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public ActionPoint() {
//      OnConstruction();
//    }

//    partial void OnConstruction();

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public ActionPoint(ActionPoint other) : this() {
//      pos_ = other.pos_ != null ? other.pos_.Clone() : null;
//      forward_ = other.forward_ != null ? other.forward_.Clone() : null;
//      type_ = other.type_;
//      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public ActionPoint Clone() {
//      return new ActionPoint(this);
//    }

//    /// <summary>Field number for the "pos" field.</summary>
//    public const int PosFieldNumber = 1;
//    private global::Protocol.ClientV3 pos_;
//    /// <summary>
//    ///坐标信息
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ClientV3 Pos {
//      get { return pos_; }
//      set {
//        pos_ = value;
//      }
//    }

//    /// <summary>Field number for the "forward" field.</summary>
//    public const int ForwardFieldNumber = 2;
//    private global::Protocol.ClientV3 forward_;
//    /// <summary>
//    ///朝向
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ClientV3 Forward {
//      get { return forward_; }
//      set {
//        forward_ = value;
//      }
//    }

//    /// <summary>Field number for the "type" field.</summary>
//    public const int TypeFieldNumber = 3;
//    private int type_;
//    /// <summary>
//    ///类型
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int Type {
//      get { return type_; }
//      set {
//        type_ = value;
//      }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override bool Equals(object other) {
//      return Equals(other as ActionPoint);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public bool Equals(ActionPoint other) {
//      if (ReferenceEquals(other, null)) {
//        return false;
//      }
//      if (ReferenceEquals(other, this)) {
//        return true;
//      }
//      if (!object.Equals(Pos, other.Pos)) return false;
//      if (!object.Equals(Forward, other.Forward)) return false;
//      if (Type != other.Type) return false;
//      return Equals(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override int GetHashCode() {
//      int hash = 1;
//      if (pos_ != null) hash ^= Pos.GetHashCode();
//      if (forward_ != null) hash ^= Forward.GetHashCode();
//      if (Type != 0) hash ^= Type.GetHashCode();
//      if (_unknownFields != null) {
//        hash ^= _unknownFields.GetHashCode();
//      }
//      return hash;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override string ToString() {
//      return pb::JsonFormatter.ToDiagnosticString(this);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void WriteTo(pb::CodedOutputStream output) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      output.WriteRawMessage(this);
//    #else
//      if (pos_ != null) {
//        output.WriteRawTag(10);
//        output.WriteMessage(Pos);
//      }
//      if (forward_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(Forward);
//      }
//      if (Type != 0) {
//        output.WriteRawTag(24);
//        output.WriteInt32(Type);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(output);
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//      if (pos_ != null) {
//        output.WriteRawTag(10);
//        output.WriteMessage(Pos);
//      }
//      if (forward_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(Forward);
//      }
//      if (Type != 0) {
//        output.WriteRawTag(24);
//        output.WriteInt32(Type);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(ref output);
//      }
//    }
//    #endif

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CalculateSize() {
//      int size = 0;
//      if (pos_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
//      }
//      if (forward_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Forward);
//      }
//      if (Type != 0) {
//        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
//      }
//      if (_unknownFields != null) {
//        size += _unknownFields.CalculateSize();
//      }
//      return size;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(ActionPoint other) {
//      if (other == null) {
//        return;
//      }
//      if (other.pos_ != null) {
//        if (pos_ == null) {
//          Pos = new global::Protocol.ClientV3();
//        }
//        Pos.MergeFrom(other.Pos);
//      }
//      if (other.forward_ != null) {
//        if (forward_ == null) {
//          Forward = new global::Protocol.ClientV3();
//        }
//        Forward.MergeFrom(other.Forward);
//      }
//      if (other.Type != 0) {
//        Type = other.Type;
//      }
//      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(pb::CodedInputStream input) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      input.ReadRawMessage(this);
//    #else
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//            break;
//          case 10: {
//            if (pos_ == null) {
//              Pos = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Pos);
//            break;
//          }
//          case 18: {
//            if (forward_ == null) {
//              Forward = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Forward);
//            break;
//          }
//          case 24: {
//            Type = input.ReadInt32();
//            break;
//          }
//        }
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//            break;
//          case 10: {
//            if (pos_ == null) {
//              Pos = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Pos);
//            break;
//          }
//          case 18: {
//            if (forward_ == null) {
//              Forward = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Forward);
//            break;
//          }
//          case 24: {
//            Type = input.ReadInt32();
//            break;
//          }
//        }
//      }
//    }
//    #endif

//  }

//  public sealed partial class TriggerAreaGroup : pb::IMessage<TriggerAreaGroup>
//  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      , pb::IBufferMessage
//  #endif
//  {
//    private static readonly pb::MessageParser<TriggerAreaGroup> _parser = new pb::MessageParser<TriggerAreaGroup>(() => new TriggerAreaGroup());
//    private pb::UnknownFieldSet _unknownFields;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pb::MessageParser<TriggerAreaGroup> Parser { get { return _parser; } }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pbr::MessageDescriptor Descriptor {
//      get { return global::Protocol.ClientLevelReflection.Descriptor.MessageTypes[3]; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    pbr::MessageDescriptor pb::IMessage.Descriptor {
//      get { return Descriptor; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public TriggerAreaGroup() {
//      OnConstruction();
//    }

//    partial void OnConstruction();

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public TriggerAreaGroup(TriggerAreaGroup other) : this() {
//      list_ = other.list_.Clone();
//      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public TriggerAreaGroup Clone() {
//      return new TriggerAreaGroup(this);
//    }

//    /// <summary>Field number for the "list" field.</summary>
//    public const int ListFieldNumber = 1;
//    private static readonly pb::FieldCodec<global::Protocol.TriggerArea> _repeated_list_codec
//        = pb::FieldCodec.ForMessage(10, global::Protocol.TriggerArea.Parser);
//    private readonly pbc::RepeatedField<global::Protocol.TriggerArea> list_ = new pbc::RepeatedField<global::Protocol.TriggerArea>();
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public pbc::RepeatedField<global::Protocol.TriggerArea> List {
//      get { return list_; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override bool Equals(object other) {
//      return Equals(other as TriggerAreaGroup);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public bool Equals(TriggerAreaGroup other) {
//      if (ReferenceEquals(other, null)) {
//        return false;
//      }
//      if (ReferenceEquals(other, this)) {
//        return true;
//      }
//      if(!list_.Equals(other.list_)) return false;
//      return Equals(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override int GetHashCode() {
//      int hash = 1;
//      hash ^= list_.GetHashCode();
//      if (_unknownFields != null) {
//        hash ^= _unknownFields.GetHashCode();
//      }
//      return hash;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override string ToString() {
//      return pb::JsonFormatter.ToDiagnosticString(this);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void WriteTo(pb::CodedOutputStream output) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      output.WriteRawMessage(this);
//    #else
//      list_.WriteTo(output, _repeated_list_codec);
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(output);
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//      list_.WriteTo(ref output, _repeated_list_codec);
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(ref output);
//      }
//    }
//    #endif

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CalculateSize() {
//      int size = 0;
//      size += list_.CalculateSize(_repeated_list_codec);
//      if (_unknownFields != null) {
//        size += _unknownFields.CalculateSize();
//      }
//      return size;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(TriggerAreaGroup other) {
//      if (other == null) {
//        return;
//      }
//      list_.Add(other.list_);
//      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(pb::CodedInputStream input) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      input.ReadRawMessage(this);
//    #else
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//            break;
//          case 10: {
//            list_.AddEntriesFrom(input, _repeated_list_codec);
//            break;
//          }
//        }
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//            break;
//          case 10: {
//            list_.AddEntriesFrom(ref input, _repeated_list_codec);
//            break;
//          }
//        }
//      }
//    }
//    #endif

//  }

//  public sealed partial class TriggerArea : pb::IMessage<TriggerArea>
//  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      , pb::IBufferMessage
//  #endif
//  {
//    private static readonly pb::MessageParser<TriggerArea> _parser = new pb::MessageParser<TriggerArea>(() => new TriggerArea());
//    private pb::UnknownFieldSet _unknownFields;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pb::MessageParser<TriggerArea> Parser { get { return _parser; } }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pbr::MessageDescriptor Descriptor {
//      get { return global::Protocol.ClientLevelReflection.Descriptor.MessageTypes[4]; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    pbr::MessageDescriptor pb::IMessage.Descriptor {
//      get { return Descriptor; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public TriggerArea() {
//      OnConstruction();
//    }

//    partial void OnConstruction();

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public TriggerArea(TriggerArea other) : this() {
//      shape_ = other.shape_;
//      size_ = other.size_ != null ? other.size_.Clone() : null;
//      condition_ = other.condition_;
//      checkLayerList_ = other.checkLayerList_.Clone();
//      effect_ = other.effect_;
//      pos_ = other.pos_ != null ? other.pos_.Clone() : null;
//      forward_ = other.forward_ != null ? other.forward_.Clone() : null;
//      cfgId_ = other.cfgId_;
//      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public TriggerArea Clone() {
//      return new TriggerArea(this);
//    }

//    /// <summary>Field number for the "shape" field.</summary>
//    public const int ShapeFieldNumber = 1;
//    private int shape_;
//    /// <summary>
//    ///形状
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int Shape {
//      get { return shape_; }
//      set {
//        shape_ = value;
//      }
//    }

//    /// <summary>Field number for the "size" field.</summary>
//    public const int SizeFieldNumber = 2;
//    private global::Protocol.ClientV3 size_;
//    /// <summary>
//    ///范围大小
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ClientV3 Size {
//      get { return size_; }
//      set {
//        size_ = value;
//      }
//    }

//    /// <summary>Field number for the "condition" field.</summary>
//    public const int ConditionFieldNumber = 3;
//    private int condition_;
//    /// <summary>
//    ///触发条件
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int Condition {
//      get { return condition_; }
//      set {
//        condition_ = value;
//      }
//    }

//    /// <summary>Field number for the "check_layer_list" field.</summary>
//    public const int CheckLayerListFieldNumber = 4;
//    private static readonly pb::FieldCodec<int> _repeated_checkLayerList_codec
//        = pb::FieldCodec.ForInt32(34);
//    private readonly pbc::RepeatedField<int> checkLayerList_ = new pbc::RepeatedField<int>();
//    /// <summary>
//    ///检测层
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public pbc::RepeatedField<int> CheckLayerList {
//      get { return checkLayerList_; }
//    }

//    /// <summary>Field number for the "effect" field.</summary>
//    public const int EffectFieldNumber = 5;
//    private int effect_;
//    /// <summary>
//    ///触发后的效果
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int Effect {
//      get { return effect_; }
//      set {
//        effect_ = value;
//      }
//    }

//    /// <summary>Field number for the "pos" field.</summary>
//    public const int PosFieldNumber = 6;
//    private global::Protocol.ClientV3 pos_;
//    /// <summary>
//    ///坐标信息
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ClientV3 Pos {
//      get { return pos_; }
//      set {
//        pos_ = value;
//      }
//    }

//    /// <summary>Field number for the "forward" field.</summary>
//    public const int ForwardFieldNumber = 7;
//    private global::Protocol.ClientV3 forward_;
//    /// <summary>
//    ///朝向
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ClientV3 Forward {
//      get { return forward_; }
//      set {
//        forward_ = value;
//      }
//    }

//    /// <summary>Field number for the "cfgId" field.</summary>
//    public const int CfgIdFieldNumber = 8;
//    private int cfgId_;
//    /// <summary>
//    ///同类型的ID、配置表的ID
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CfgId {
//      get { return cfgId_; }
//      set {
//        cfgId_ = value;
//      }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override bool Equals(object other) {
//      return Equals(other as TriggerArea);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public bool Equals(TriggerArea other) {
//      if (ReferenceEquals(other, null)) {
//        return false;
//      }
//      if (ReferenceEquals(other, this)) {
//        return true;
//      }
//      if (Shape != other.Shape) return false;
//      if (!object.Equals(Size, other.Size)) return false;
//      if (Condition != other.Condition) return false;
//      if(!checkLayerList_.Equals(other.checkLayerList_)) return false;
//      if (Effect != other.Effect) return false;
//      if (!object.Equals(Pos, other.Pos)) return false;
//      if (!object.Equals(Forward, other.Forward)) return false;
//      if (CfgId != other.CfgId) return false;
//      return Equals(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override int GetHashCode() {
//      int hash = 1;
//      if (Shape != 0) hash ^= Shape.GetHashCode();
//      if (size_ != null) hash ^= Size.GetHashCode();
//      if (Condition != 0) hash ^= Condition.GetHashCode();
//      hash ^= checkLayerList_.GetHashCode();
//      if (Effect != 0) hash ^= Effect.GetHashCode();
//      if (pos_ != null) hash ^= Pos.GetHashCode();
//      if (forward_ != null) hash ^= Forward.GetHashCode();
//      if (CfgId != 0) hash ^= CfgId.GetHashCode();
//      if (_unknownFields != null) {
//        hash ^= _unknownFields.GetHashCode();
//      }
//      return hash;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override string ToString() {
//      return pb::JsonFormatter.ToDiagnosticString(this);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void WriteTo(pb::CodedOutputStream output) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      output.WriteRawMessage(this);
//    #else
//      if (Shape != 0) {
//        output.WriteRawTag(8);
//        output.WriteInt32(Shape);
//      }
//      if (size_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(Size);
//      }
//      if (Condition != 0) {
//        output.WriteRawTag(24);
//        output.WriteInt32(Condition);
//      }
//      checkLayerList_.WriteTo(output, _repeated_checkLayerList_codec);
//      if (Effect != 0) {
//        output.WriteRawTag(40);
//        output.WriteInt32(Effect);
//      }
//      if (pos_ != null) {
//        output.WriteRawTag(50);
//        output.WriteMessage(Pos);
//      }
//      if (forward_ != null) {
//        output.WriteRawTag(58);
//        output.WriteMessage(Forward);
//      }
//      if (CfgId != 0) {
//        output.WriteRawTag(64);
//        output.WriteInt32(CfgId);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(output);
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//      if (Shape != 0) {
//        output.WriteRawTag(8);
//        output.WriteInt32(Shape);
//      }
//      if (size_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(Size);
//      }
//      if (Condition != 0) {
//        output.WriteRawTag(24);
//        output.WriteInt32(Condition);
//      }
//      checkLayerList_.WriteTo(ref output, _repeated_checkLayerList_codec);
//      if (Effect != 0) {
//        output.WriteRawTag(40);
//        output.WriteInt32(Effect);
//      }
//      if (pos_ != null) {
//        output.WriteRawTag(50);
//        output.WriteMessage(Pos);
//      }
//      if (forward_ != null) {
//        output.WriteRawTag(58);
//        output.WriteMessage(Forward);
//      }
//      if (CfgId != 0) {
//        output.WriteRawTag(64);
//        output.WriteInt32(CfgId);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(ref output);
//      }
//    }
//    #endif

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CalculateSize() {
//      int size = 0;
//      if (Shape != 0) {
//        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Shape);
//      }
//      if (size_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Size);
//      }
//      if (Condition != 0) {
//        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Condition);
//      }
//      size += checkLayerList_.CalculateSize(_repeated_checkLayerList_codec);
//      if (Effect != 0) {
//        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Effect);
//      }
//      if (pos_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
//      }
//      if (forward_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Forward);
//      }
//      if (CfgId != 0) {
//        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CfgId);
//      }
//      if (_unknownFields != null) {
//        size += _unknownFields.CalculateSize();
//      }
//      return size;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(TriggerArea other) {
//      if (other == null) {
//        return;
//      }
//      if (other.Shape != 0) {
//        Shape = other.Shape;
//      }
//      if (other.size_ != null) {
//        if (size_ == null) {
//          Size = new global::Protocol.ClientV3();
//        }
//        Size.MergeFrom(other.Size);
//      }
//      if (other.Condition != 0) {
//        Condition = other.Condition;
//      }
//      checkLayerList_.Add(other.checkLayerList_);
//      if (other.Effect != 0) {
//        Effect = other.Effect;
//      }
//      if (other.pos_ != null) {
//        if (pos_ == null) {
//          Pos = new global::Protocol.ClientV3();
//        }
//        Pos.MergeFrom(other.Pos);
//      }
//      if (other.forward_ != null) {
//        if (forward_ == null) {
//          Forward = new global::Protocol.ClientV3();
//        }
//        Forward.MergeFrom(other.Forward);
//      }
//      if (other.CfgId != 0) {
//        CfgId = other.CfgId;
//      }
//      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(pb::CodedInputStream input) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      input.ReadRawMessage(this);
//    #else
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//            break;
//          case 8: {
//            Shape = input.ReadInt32();
//            break;
//          }
//          case 18: {
//            if (size_ == null) {
//              Size = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Size);
//            break;
//          }
//          case 24: {
//            Condition = input.ReadInt32();
//            break;
//          }
//          case 34:
//          case 32: {
//            checkLayerList_.AddEntriesFrom(input, _repeated_checkLayerList_codec);
//            break;
//          }
//          case 40: {
//            Effect = input.ReadInt32();
//            break;
//          }
//          case 50: {
//            if (pos_ == null) {
//              Pos = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Pos);
//            break;
//          }
//          case 58: {
//            if (forward_ == null) {
//              Forward = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Forward);
//            break;
//          }
//          case 64: {
//            CfgId = input.ReadInt32();
//            break;
//          }
//        }
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//            break;
//          case 8: {
//            Shape = input.ReadInt32();
//            break;
//          }
//          case 18: {
//            if (size_ == null) {
//              Size = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Size);
//            break;
//          }
//          case 24: {
//            Condition = input.ReadInt32();
//            break;
//          }
//          case 34:
//          case 32: {
//            checkLayerList_.AddEntriesFrom(ref input, _repeated_checkLayerList_codec);
//            break;
//          }
//          case 40: {
//            Effect = input.ReadInt32();
//            break;
//          }
//          case 50: {
//            if (pos_ == null) {
//              Pos = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Pos);
//            break;
//          }
//          case 58: {
//            if (forward_ == null) {
//              Forward = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Forward);
//            break;
//          }
//          case 64: {
//            CfgId = input.ReadInt32();
//            break;
//          }
//        }
//      }
//    }
//    #endif

//  }

//  /// <summary>
//  ///鹅鸭杀会议室，坐标出生点
//  /// </summary>
//  public sealed partial class EysVoteRoom : pb::IMessage<EysVoteRoom>
//  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      , pb::IBufferMessage
//  #endif
//  {
//    private static readonly pb::MessageParser<EysVoteRoom> _parser = new pb::MessageParser<EysVoteRoom>(() => new EysVoteRoom());
//    private pb::UnknownFieldSet _unknownFields;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pb::MessageParser<EysVoteRoom> Parser { get { return _parser; } }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pbr::MessageDescriptor Descriptor {
//      get { return global::Protocol.ClientLevelReflection.Descriptor.MessageTypes[5]; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    pbr::MessageDescriptor pb::IMessage.Descriptor {
//      get { return Descriptor; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public EysVoteRoom() {
//      OnConstruction();
//    }

//    partial void OnConstruction();

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public EysVoteRoom(EysVoteRoom other) : this() {
//      list_ = other.list_.Clone();
//      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public EysVoteRoom Clone() {
//      return new EysVoteRoom(this);
//    }

//    /// <summary>Field number for the "list" field.</summary>
//    public const int ListFieldNumber = 1;
//    private static readonly pb::FieldCodec<global::Protocol.EysVoteItem> _repeated_list_codec
//        = pb::FieldCodec.ForMessage(10, global::Protocol.EysVoteItem.Parser);
//    private readonly pbc::RepeatedField<global::Protocol.EysVoteItem> list_ = new pbc::RepeatedField<global::Protocol.EysVoteItem>();
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public pbc::RepeatedField<global::Protocol.EysVoteItem> List {
//      get { return list_; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override bool Equals(object other) {
//      return Equals(other as EysVoteRoom);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public bool Equals(EysVoteRoom other) {
//      if (ReferenceEquals(other, null)) {
//        return false;
//      }
//      if (ReferenceEquals(other, this)) {
//        return true;
//      }
//      if(!list_.Equals(other.list_)) return false;
//      return Equals(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override int GetHashCode() {
//      int hash = 1;
//      hash ^= list_.GetHashCode();
//      if (_unknownFields != null) {
//        hash ^= _unknownFields.GetHashCode();
//      }
//      return hash;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override string ToString() {
//      return pb::JsonFormatter.ToDiagnosticString(this);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void WriteTo(pb::CodedOutputStream output) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      output.WriteRawMessage(this);
//    #else
//      list_.WriteTo(output, _repeated_list_codec);
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(output);
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//      list_.WriteTo(ref output, _repeated_list_codec);
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(ref output);
//      }
//    }
//    #endif

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CalculateSize() {
//      int size = 0;
//      size += list_.CalculateSize(_repeated_list_codec);
//      if (_unknownFields != null) {
//        size += _unknownFields.CalculateSize();
//      }
//      return size;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(EysVoteRoom other) {
//      if (other == null) {
//        return;
//      }
//      list_.Add(other.list_);
//      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(pb::CodedInputStream input) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      input.ReadRawMessage(this);
//    #else
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//            break;
//          case 10: {
//            list_.AddEntriesFrom(input, _repeated_list_codec);
//            break;
//          }
//        }
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//            break;
//          case 10: {
//            list_.AddEntriesFrom(ref input, _repeated_list_codec);
//            break;
//          }
//        }
//      }
//    }
//    #endif

//  }

//  public sealed partial class EysVoteItem : pb::IMessage<EysVoteItem>
//  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      , pb::IBufferMessage
//  #endif
//  {
//    private static readonly pb::MessageParser<EysVoteItem> _parser = new pb::MessageParser<EysVoteItem>(() => new EysVoteItem());
//    private pb::UnknownFieldSet _unknownFields;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pb::MessageParser<EysVoteItem> Parser { get { return _parser; } }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pbr::MessageDescriptor Descriptor {
//      get { return global::Protocol.ClientLevelReflection.Descriptor.MessageTypes[6]; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    pbr::MessageDescriptor pb::IMessage.Descriptor {
//      get { return Descriptor; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public EysVoteItem() {
//      OnConstruction();
//    }

//    partial void OnConstruction();

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public EysVoteItem(EysVoteItem other) : this() {
//      pos_ = other.pos_ != null ? other.pos_.Clone() : null;
//      forward_ = other.forward_ != null ? other.forward_.Clone() : null;
//      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public EysVoteItem Clone() {
//      return new EysVoteItem(this);
//    }

//    /// <summary>Field number for the "pos" field.</summary>
//    public const int PosFieldNumber = 1;
//    private global::Protocol.ClientV3 pos_;
//    /// <summary>
//    ///坐标信息
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ClientV3 Pos {
//      get { return pos_; }
//      set {
//        pos_ = value;
//      }
//    }

//    /// <summary>Field number for the "forward" field.</summary>
//    public const int ForwardFieldNumber = 2;
//    private global::Protocol.ClientV3 forward_;
//    /// <summary>
//    ///朝向
//    /// </summary>
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ClientV3 Forward {
//      get { return forward_; }
//      set {
//        forward_ = value;
//      }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override bool Equals(object other) {
//      return Equals(other as EysVoteItem);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public bool Equals(EysVoteItem other) {
//      if (ReferenceEquals(other, null)) {
//        return false;
//      }
//      if (ReferenceEquals(other, this)) {
//        return true;
//      }
//      if (!object.Equals(Pos, other.Pos)) return false;
//      if (!object.Equals(Forward, other.Forward)) return false;
//      return Equals(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override int GetHashCode() {
//      int hash = 1;
//      if (pos_ != null) hash ^= Pos.GetHashCode();
//      if (forward_ != null) hash ^= Forward.GetHashCode();
//      if (_unknownFields != null) {
//        hash ^= _unknownFields.GetHashCode();
//      }
//      return hash;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override string ToString() {
//      return pb::JsonFormatter.ToDiagnosticString(this);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void WriteTo(pb::CodedOutputStream output) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      output.WriteRawMessage(this);
//    #else
//      if (pos_ != null) {
//        output.WriteRawTag(10);
//        output.WriteMessage(Pos);
//      }
//      if (forward_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(Forward);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(output);
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//      if (pos_ != null) {
//        output.WriteRawTag(10);
//        output.WriteMessage(Pos);
//      }
//      if (forward_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(Forward);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(ref output);
//      }
//    }
//    #endif

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CalculateSize() {
//      int size = 0;
//      if (pos_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
//      }
//      if (forward_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Forward);
//      }
//      if (_unknownFields != null) {
//        size += _unknownFields.CalculateSize();
//      }
//      return size;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(EysVoteItem other) {
//      if (other == null) {
//        return;
//      }
//      if (other.pos_ != null) {
//        if (pos_ == null) {
//          Pos = new global::Protocol.ClientV3();
//        }
//        Pos.MergeFrom(other.Pos);
//      }
//      if (other.forward_ != null) {
//        if (forward_ == null) {
//          Forward = new global::Protocol.ClientV3();
//        }
//        Forward.MergeFrom(other.Forward);
//      }
//      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(pb::CodedInputStream input) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      input.ReadRawMessage(this);
//    #else
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//            break;
//          case 10: {
//            if (pos_ == null) {
//              Pos = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Pos);
//            break;
//          }
//          case 18: {
//            if (forward_ == null) {
//              Forward = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Forward);
//            break;
//          }
//        }
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//            break;
//          case 10: {
//            if (pos_ == null) {
//              Pos = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Pos);
//            break;
//          }
//          case 18: {
//            if (forward_ == null) {
//              Forward = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Forward);
//            break;
//          }
//        }
//      }
//    }
//    #endif

//  }

//  public sealed partial class ClientV3 : pb::IMessage<ClientV3>
//  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      , pb::IBufferMessage
//  #endif
//  {
//    private static readonly pb::MessageParser<ClientV3> _parser = new pb::MessageParser<ClientV3>(() => new ClientV3());
//    private pb::UnknownFieldSet _unknownFields;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pb::MessageParser<ClientV3> Parser { get { return _parser; } }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pbr::MessageDescriptor Descriptor {
//      get { return global::Protocol.ClientLevelReflection.Descriptor.MessageTypes[7]; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    pbr::MessageDescriptor pb::IMessage.Descriptor {
//      get { return Descriptor; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public ClientV3() {
//      OnConstruction();
//    }

//    partial void OnConstruction();

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public ClientV3(ClientV3 other) : this() {
//      x_ = other.x_;
//      y_ = other.y_;
//      z_ = other.z_;
//      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public ClientV3 Clone() {
//      return new ClientV3(this);
//    }

//    /// <summary>Field number for the "x" field.</summary>
//    public const int XFieldNumber = 1;
//    private int x_;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int X {
//      get { return x_; }
//      set {
//        x_ = value;
//      }
//    }

//    /// <summary>Field number for the "y" field.</summary>
//    public const int YFieldNumber = 2;
//    private int y_;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int Y {
//      get { return y_; }
//      set {
//        y_ = value;
//      }
//    }

//    /// <summary>Field number for the "z" field.</summary>
//    public const int ZFieldNumber = 3;
//    private int z_;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int Z {
//      get { return z_; }
//      set {
//        z_ = value;
//      }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override bool Equals(object other) {
//      return Equals(other as ClientV3);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public bool Equals(ClientV3 other) {
//      if (ReferenceEquals(other, null)) {
//        return false;
//      }
//      if (ReferenceEquals(other, this)) {
//        return true;
//      }
//      if (X != other.X) return false;
//      if (Y != other.Y) return false;
//      if (Z != other.Z) return false;
//      return Equals(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override int GetHashCode() {
//      int hash = 1;
//      if (X != 0) hash ^= X.GetHashCode();
//      if (Y != 0) hash ^= Y.GetHashCode();
//      if (Z != 0) hash ^= Z.GetHashCode();
//      if (_unknownFields != null) {
//        hash ^= _unknownFields.GetHashCode();
//      }
//      return hash;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override string ToString() {
//      return pb::JsonFormatter.ToDiagnosticString(this);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void WriteTo(pb::CodedOutputStream output) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      output.WriteRawMessage(this);
//    #else
//      if (X != 0) {
//        output.WriteRawTag(8);
//        output.WriteInt32(X);
//      }
//      if (Y != 0) {
//        output.WriteRawTag(16);
//        output.WriteInt32(Y);
//      }
//      if (Z != 0) {
//        output.WriteRawTag(24);
//        output.WriteInt32(Z);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(output);
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//      if (X != 0) {
//        output.WriteRawTag(8);
//        output.WriteInt32(X);
//      }
//      if (Y != 0) {
//        output.WriteRawTag(16);
//        output.WriteInt32(Y);
//      }
//      if (Z != 0) {
//        output.WriteRawTag(24);
//        output.WriteInt32(Z);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(ref output);
//      }
//    }
//    #endif

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CalculateSize() {
//      int size = 0;
//      if (X != 0) {
//        size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
//      }
//      if (Y != 0) {
//        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
//      }
//      if (Z != 0) {
//        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Z);
//      }
//      if (_unknownFields != null) {
//        size += _unknownFields.CalculateSize();
//      }
//      return size;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(ClientV3 other) {
//      if (other == null) {
//        return;
//      }
//      if (other.X != 0) {
//        X = other.X;
//      }
//      if (other.Y != 0) {
//        Y = other.Y;
//      }
//      if (other.Z != 0) {
//        Z = other.Z;
//      }
//      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(pb::CodedInputStream input) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      input.ReadRawMessage(this);
//    #else
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//            break;
//          case 8: {
//            X = input.ReadInt32();
//            break;
//          }
//          case 16: {
//            Y = input.ReadInt32();
//            break;
//          }
//          case 24: {
//            Z = input.ReadInt32();
//            break;
//          }
//        }
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//            break;
//          case 8: {
//            X = input.ReadInt32();
//            break;
//          }
//          case 16: {
//            Y = input.ReadInt32();
//            break;
//          }
//          case 24: {
//            Z = input.ReadInt32();
//            break;
//          }
//        }
//      }
//    }
//    #endif

//  }

//  public sealed partial class GamePlayTriggerArea : pb::IMessage<GamePlayTriggerArea>
//  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      , pb::IBufferMessage
//  #endif
//  {
//    private static readonly pb::MessageParser<GamePlayTriggerArea> _parser = new pb::MessageParser<GamePlayTriggerArea>(() => new GamePlayTriggerArea());
//    private pb::UnknownFieldSet _unknownFields;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pb::MessageParser<GamePlayTriggerArea> Parser { get { return _parser; } }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public static pbr::MessageDescriptor Descriptor {
//      get { return global::Protocol.ClientLevelReflection.Descriptor.MessageTypes[8]; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    pbr::MessageDescriptor pb::IMessage.Descriptor {
//      get { return Descriptor; }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public GamePlayTriggerArea() {
//      OnConstruction();
//    }

//    partial void OnConstruction();

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public GamePlayTriggerArea(GamePlayTriggerArea other) : this() {
//      pos_ = other.pos_ != null ? other.pos_.Clone() : null;
//      forward_ = other.forward_ != null ? other.forward_.Clone() : null;
//      size_ = other.size_;
//      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public GamePlayTriggerArea Clone() {
//      return new GamePlayTriggerArea(this);
//    }

//    /// <summary>Field number for the "pos" field.</summary>
//    public const int PosFieldNumber = 1;
//    private global::Protocol.ClientV3 pos_;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ClientV3 Pos {
//      get { return pos_; }
//      set {
//        pos_ = value;
//      }
//    }

//    /// <summary>Field number for the "forward" field.</summary>
//    public const int ForwardFieldNumber = 2;
//    private global::Protocol.ClientV3 forward_;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public global::Protocol.ClientV3 Forward {
//      get { return forward_; }
//      set {
//        forward_ = value;
//      }
//    }

//    /// <summary>Field number for the "size" field.</summary>
//    public const int SizeFieldNumber = 3;
//    private int size_;
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int Size {
//      get { return size_; }
//      set {
//        size_ = value;
//      }
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override bool Equals(object other) {
//      return Equals(other as GamePlayTriggerArea);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public bool Equals(GamePlayTriggerArea other) {
//      if (ReferenceEquals(other, null)) {
//        return false;
//      }
//      if (ReferenceEquals(other, this)) {
//        return true;
//      }
//      if (!object.Equals(Pos, other.Pos)) return false;
//      if (!object.Equals(Forward, other.Forward)) return false;
//      if (Size != other.Size) return false;
//      return Equals(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override int GetHashCode() {
//      int hash = 1;
//      if (pos_ != null) hash ^= Pos.GetHashCode();
//      if (forward_ != null) hash ^= Forward.GetHashCode();
//      if (Size != 0) hash ^= Size.GetHashCode();
//      if (_unknownFields != null) {
//        hash ^= _unknownFields.GetHashCode();
//      }
//      return hash;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public override string ToString() {
//      return pb::JsonFormatter.ToDiagnosticString(this);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void WriteTo(pb::CodedOutputStream output) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      output.WriteRawMessage(this);
//    #else
//      if (pos_ != null) {
//        output.WriteRawTag(10);
//        output.WriteMessage(Pos);
//      }
//      if (forward_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(Forward);
//      }
//      if (Size != 0) {
//        output.WriteRawTag(24);
//        output.WriteInt32(Size);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(output);
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//      if (pos_ != null) {
//        output.WriteRawTag(10);
//        output.WriteMessage(Pos);
//      }
//      if (forward_ != null) {
//        output.WriteRawTag(18);
//        output.WriteMessage(Forward);
//      }
//      if (Size != 0) {
//        output.WriteRawTag(24);
//        output.WriteInt32(Size);
//      }
//      if (_unknownFields != null) {
//        _unknownFields.WriteTo(ref output);
//      }
//    }
//    #endif

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public int CalculateSize() {
//      int size = 0;
//      if (pos_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
//      }
//      if (forward_ != null) {
//        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Forward);
//      }
//      if (Size != 0) {
//        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Size);
//      }
//      if (_unknownFields != null) {
//        size += _unknownFields.CalculateSize();
//      }
//      return size;
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(GamePlayTriggerArea other) {
//      if (other == null) {
//        return;
//      }
//      if (other.pos_ != null) {
//        if (pos_ == null) {
//          Pos = new global::Protocol.ClientV3();
//        }
//        Pos.MergeFrom(other.Pos);
//      }
//      if (other.forward_ != null) {
//        if (forward_ == null) {
//          Forward = new global::Protocol.ClientV3();
//        }
//        Forward.MergeFrom(other.Forward);
//      }
//      if (other.Size != 0) {
//        Size = other.Size;
//      }
//      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//    }

//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    public void MergeFrom(pb::CodedInputStream input) {
//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//      input.ReadRawMessage(this);
//    #else
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//            break;
//          case 10: {
//            if (pos_ == null) {
//              Pos = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Pos);
//            break;
//          }
//          case 18: {
//            if (forward_ == null) {
//              Forward = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Forward);
//            break;
//          }
//          case 24: {
//            Size = input.ReadInt32();
//            break;
//          }
//        }
//      }
//    #endif
//    }

//    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//      uint tag;
//      while ((tag = input.ReadTag()) != 0) {
//        switch(tag) {
//          default:
//            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//            break;
//          case 10: {
//            if (pos_ == null) {
//              Pos = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Pos);
//            break;
//          }
//          case 18: {
//            if (forward_ == null) {
//              Forward = new global::Protocol.ClientV3();
//            }
//            input.ReadMessage(Forward);
//            break;
//          }
//          case 24: {
//            Size = input.ReadInt32();
//            break;
//          }
//        }
//      }
//    }
//    #endif

//  }

//  #endregion

//}

//#endregion Designer generated code
